// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zamyad.Exemption.Data.EdariDB
{
    public partial class CostCenter
    {
        public string CostCode { get; set; }
        public string CostDesc { get; set; }
        public string Active { get; set; }
        public string TotCostCode { get; set; }
        public decimal HoliOverFactor { get; set; }
        public decimal AcordFactor { get; set; }
        public string Produceorsupport { get; set; }
        public decimal BossSpecialFactor { get; set; }
        public decimal PostalRightsFactor { get; set; }
        public decimal ProductionRightsFactor { get; set; }
        public decimal WorkEnvCondRightsFactor { get; set; }
    }
}