// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zamyad.Exemption.Data.SocialDB
{
    public partial class PersExemptionsView
    {
        public int Id { get; set; }
        public string PersNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobDesc { get; set; }
        public string CostCode { get; set; }
        public string CostDesc { get; set; }
        public string NewcostCode { get; set; }
        public string Newcostdesc { get; set; }
        public string TypeDesc { get; set; }
        public string CategoryDesc { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Comment { get; set; }
        public string IsBadv { get; set; }
        public string IsTebKar { get; set; }
        public string IsSayer { get; set; }
        public string IsDoreyi { get; set; }
        public string IsShoghli { get; set; }
        public string Explanation { get; set; }
        public string Behdasht { get; set; }
        public string IsSalamatCommittee { get; set; }
        public string IsCommission { get; set; }
        public int ExemptionId { get; set; }
    }
}