// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zamyad.Exemption.Data.SocialDB
{
    public partial class PersHadeseView
    {
        public int Id { get; set; }
        public string PersNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AccidentMogheyiat { get; set; }
        public string AccidentMahal { get; set; }
        public string RegDate { get; set; }
        public string AccDate { get; set; }
        public string AccTime { get; set; }
        public string StartWorkingTime { get; set; }
        public int? WorkDuration { get; set; }
        public string Description { get; set; }
        public string AccType { get; set; }
        public string InjuryType { get; set; }
        public string BodyPart { get; set; }
        public string DispatchedTo { get; set; }
        public int? WastedDuration { get; set; }
        public string NeedRest { get; set; }
        public string CostDesc { get; set; }
        public string CostCode { get; set; }
    }
}