// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Zamyad.Exemption.Data.SocialDB
{
    public partial class PersRestView
    {
        public int Id { get; set; }
        public string PersNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CostCode { get; set; }
        public string CostDesc { get; set; }
        public string TotCostCode { get; set; }
        public string DiseaseType { get; set; }
        public string Fdate { get; set; }
        public string Edate { get; set; }
        public string IsLocalDoc { get; set; }
        public string IsGeneralDoc { get; set; }
        public string DocName { get; set; }
        public string Explanation { get; set; }
    }
}